version: "3"

set:
  - nounset

tasks:
  new:
    cmds:
      - cargo new {{.CLI_ARGS}}
      - touch {{.CLI_ARGS}}/input.txt
    silent: true
  run:
    cmds:
      - cargo run {{.CLI_ARGS}}
    silent: true
